// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./keyValue";

export type WorkspaceEnvironment = { id: string, name: string, variables: Array<KeyValue>, };
