// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMethod } from "./httpMethod";
import type { KeyValue } from "./keyValue";
import type { RequestBody } from "./requestBody";
import type { ScriptConfig } from "./scriptConfig";

export type FirvRequest = { id: string, name: string, method: HttpMethod, url: string, headers: Array<KeyValue>, params: Array<KeyValue>, body: RequestBody, scripts: ScriptConfig, };
