// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowStep } from "./flowStep";

export type FirvFlow = { id: string, name: string, steps: Array<FlowStep>, };
