// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workspace } from "./workspace";

export type FirvManifest = { version: string, name: string, workspace: Workspace, 
/**
 * Stable identifier for this workspace, used to namespace entries in the
 * global secret store (`~/.firv/secrets.yaml`) independent of the
 * workspace's filesystem path (which can be moved/renamed).
 */
workspace_id: string, };
