// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A flow-scoped variable passed into a step before it runs. The `value` may
 * reference variables produced by earlier steps with `{{var}}` syntax.
 */
export type FlowInputVariable = { key: string, value: string, enabled: boolean, };
