// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FlowExtractionRule } from "./flowExtractionRule";
import type { FlowInputVariable } from "./flowInputVariable";

export type FlowStep = { request_id: string, 
/**
 * Variables passed into this step before it runs. The `value` may
 * reference variables produced by earlier steps with `{{var}}` syntax.
 * Alias `overrides` preserves flow files saved before this rename.
 */
input_variables: Array<FlowInputVariable>, 
/**
 * Variables extracted from this step's response and exported to the flow
 * context for use by later steps, in addition to the step's own persisted
 * `response_extractions`.
 */
export_variables: Array<FlowExtractionRule>, 
/**
 * Suppresses this step's own persisted `before_run` chain when run as part
 * of the flow, without mutating the underlying request.
 */
skip_before_chain: boolean, 
/**
 * Suppresses this step's own persisted `on_success` chain_steps when run
 * as part of the flow, without mutating the underlying request.
 */
skip_on_success_chain: boolean, 
/**
 * Suppresses this step's own persisted `on_failure` chain_steps when run
 * as part of the flow, without mutating the underlying request.
 */
skip_on_failure_chain: boolean, };
