// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionSource } from "./extractionSource";

/**
 * A flow-scoped response extraction that publishes a value into the flow
 * context for use by later steps, without editing the underlying request.
 */
export type FlowExtractionRule = { target: string, source: ExtractionSource, pattern: string, enabled: boolean, };
