// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GrpcStreamingMode } from "./grpcStreamingMode";
import type { KeyValue } from "./keyValue";

export type GrpcRequest = { id: string, name: string, url: string, proto_source: string, service: string, method: string, streaming_mode: GrpcStreamingMode, metadata: Array<KeyValue>, message: string, };
