// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarKind } from "./sidebarKind";

export type HydratedSidebarItem = { id: string, kind: SidebarKind, };
