// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type KeyValue = { key: string, value: string, enabled: boolean, 
/**
 * When set, the effective value of this variable is resolved from the named
 * entry in the workspace's secret store (`~/.firv/secrets.yaml`) instead of
 * `value`. `value` is left empty and never persisted for secret-referencing rows.
 */
secret_ref?: string | null, };
