// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RequestChainStep } from "./requestChainStep";
import type { RequestExtractionRule } from "./requestExtractionRule";

export type RequestTransforms = { pre_request_template: string | null, response_extractions: Array<RequestExtractionRule>, chain_steps: Array<RequestChainStep>, };
