// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestVariable = { key: string, value: string, 
/**
 * Id of a secret in the workspace's secret store. When set, the effective
 * value is resolved from that secret instead of `value` (which is left empty).
 */
secret_ref: string | null, };
