// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type RequestTransforms = { pre_request: string | null, post_response: string | null, };
