// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./keyValue";

export type RequestBody = { "mode": "none" } | { "mode": "json", "data": string } | { "mode": "raw", "data": string } | { "mode": "formdata", "data": Array<KeyValue> };
