// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptConfig } from "./scriptConfig";

export type SidebarItem = { "type": "folder", name: string, items: Array<SidebarItem>, scripts: ScriptConfig, } | { "type": "request", id: string, name: string, };
