// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HttpMethod } from "./httpMethod";

export type SidebarItem = { "type": "folder", name: string, items: Array<SidebarItem>, } | { "type": "request", id: string, name: string, method: HttpMethod, } | { "type": "ws", id: string, name: string, };
