// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ScriptConfig } from "./scriptConfig";
import type { SidebarItem } from "./sidebarItem";

export type Workspace = { order: Array<SidebarItem>, globals: { [key in string]: string }, scripts: ScriptConfig, };
