// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeyValue } from "./keyValue";
import type { SidebarItem } from "./sidebarItem";

export type Workspace = { order: Array<SidebarItem>, globals: Array<KeyValue>, };
