// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HydratedSidebarItem } from "./hydratedSidebarItem";

export type HydratedTree = { items: Array<HydratedSidebarItem>, orphans: Array<string>, };
