// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ExtractionSource } from "./extractionSource";

export type RequestExtractionRule = { target: string, source: ExtractionSource, pattern: string, };
