// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChainCondition } from "./chainCondition";

export type RequestChainStep = { when: ChainCondition, next_request_id: string, };
