// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Workspace } from "./Workspace";

export type FirvManifest = { version: string, name: string, workspace: Workspace, };
