// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SidebarItem } from "./SidebarItem";

export type Workspace = { order: Array<SidebarItem>, globals: { [key in string]: string }, };
